# Pandas — les fondamentaux (cours)

Cellules d'exemple à **exécuter** pour voir pandas tourner. Contexte : une petite table de salariés.
Les exercices (contexte différent : des villes) sont tout en bas.

### Import + Series / DataFrame

In [2]:
import pandas as pd        # convention : pandas sous l'alias "pd"

# Une Series = une seule colonne (1D) avec un index 0,1,2...
salaires = pd.Series([38000, 41000, 45000])
print(salaires)

0    38000
1    41000
2    45000
dtype: int64

In [3]:
# Un DataFrame = un tableau ; chaque clé du dict = une colonne
df = pd.DataFrame({
    "nom": ["Alice", "Bob", "Chloé"],
    "salaire": [38000, 41000, 45000],
    "service": ["Data", "Data", "RH"],
})
df

     nom  salaire service
0  Alice    38000    Data
1    Bob    41000    Data
2  Chloé    45000      RH

### Lire un CSV (pour info) + inspecter

In [4]:
# Sur un vrai fichier : df = pd.read_csv("data/employes.csv")
# Ici on inspecte le df créé au-dessus :
print(df.shape)     # (nb_lignes, nb_colonnes)
print(df.columns)   # noms de colonnes
print(df.dtypes)    # type de chaque colonne
df.describe()       # stats des colonnes numériques

(3, 3)
Index(['nom', 'salaire', 'service'], dtype='str')
nom          str
salaire    int64
service      str
dtype: object

            salaire
count      3.000000
mean   41333.333333
std     3511.884584
min    38000.000000
25%    39500.000000
50%    41000.000000
75%    43000.000000
max    45000.000000

### Sélectionner des colonnes

In [5]:
df["salaire"]            # une colonne -> Series

0    38000
1    41000
2    45000
Name: salaire, dtype: int64

In [6]:
df[["nom", "salaire"]]   # plusieurs colonnes (liste de noms) -> DataFrame

     nom  salaire
0  Alice    38000
1    Bob    41000
2  Chloé    45000

### loc (étiquette) vs iloc (position)

In [7]:
print(df.loc[0, "nom"])   # loc = par étiquette : ligne d'index 0, colonne "nom"
print(df.iloc[0, 1])      # iloc = par position : 1re ligne, 2e colonne
df.iloc[0:2]              # positions 0 et 1 (2 EXCLUE) ; avec loc, 0:2 inclurait 2

Alice
38000

     nom  salaire service
0  Alice    38000    Data
1    Bob    41000    Data

### Filtrage booléen

In [8]:
df[df["salaire"] > 40000]                                  # une condition

     nom  salaire service
1    Bob    41000    Data
2  Chloé    45000      RH

In [9]:
df[(df["salaire"] > 40000) & (df["service"] == "Data")]    # ET : () autour de chaque condition, & pour combiner

   nom  salaire service
1  Bob    41000    Data

### Trier + colonne calculée

In [10]:
df.sort_values("salaire", ascending=False)   # tri décroissant (renvoie une copie)

     nom  salaire service
2  Chloé    45000      RH
1    Bob    41000    Data
0  Alice    38000    Data

In [11]:
df["salaire_annuel"] = df["salaire"] * 12    # nouvelle colonne sur toute la colonne, sans boucle

# Exercices

Dataset : `data/villes.csv` (villes françaises : population, superficie en km², région).
Écris ton code dans les cellules vides sous chaque énoncé.

1. Importe pandas, charge `data/villes.csv` dans `villes`, affiche les **3 premières lignes**.
2. Inspecte : `shape`, types des colonnes, `describe`. Combien de villes ? Quelles colonnes numériques ?
3. Affiche **uniquement** les colonnes `ville` et `population`.
4. Avec `iloc`, affiche la **2e ligne**. Avec `loc`, la valeur `ville` de la ligne d'index `0`.
5. Filtre : villes de **plus de 200 000 habitants**.
6. Filtre multiple : région `"Normandie"` **et** plus de 100 000 habitants.
7. Tri par population **décroissante**. La plus peuplée ?
8. Colonne calculée `densite` = population / superficie, puis tri par densité décroissante.
9. Réflexion (pas de code) : différence entre `loc` et `iloc` ?

In [12]:
## 1
import pandas as pd

df = pd.read_csv("data/villes.csv")
df

          ville  population  superficie                      region
0         Paris     2133111       105.4               Île-de-France
1     Marseille      873076       240.6  Provence-Alpes-Côte d'Azur
2          Lyon      522969        47.9        Auvergne-Rhône-Alpes
3      Toulouse      498003       118.3                   Occitanie
4          Nice      342669        71.9  Provence-Alpes-Côte d'Azur
5        Nantes      323204        65.2            Pays de la Loire
6   Montpellier      299096        56.9                   Occitanie
7    Strasbourg      291313        78.3                   Grand Est
8      Bordeaux      259809        49.4          Nouvelle-Aquitaine
9         Lille      236234        34.8             Hauts-de-France
10       Rennes      222485        50.4                    Bretagne
11        Reims      181194        46.9                   Grand Est
12     Le Havre      165830        46.9                   Normandie
13        Rouen      114083        21.4                   Normandie
14         Caen      105354        25.7                   Normandie

In [13]:
## 2
print(df.describe(), "\n") 
print(df.shape, "\n")
print(df.columns, "\n")
print(df.dtypes)

         population  superficie
count  1.500000e+01   15.000000
mean   4.378953e+05   70.666667
std    5.078737e+05   54.036055
min    1.053540e+05   21.400000
25%    2.018395e+05   46.900000
50%    2.913130e+05   50.400000
75%    4.203360e+05   75.100000
max    2.133111e+06  240.600000

(15, 4)

Index(['ville', 'population', 'superficie', 'region'], dtype='str')

ville             str
population      int64
superficie    float64
region            str
dtype: object

In [14]:
## 3
df[['ville', 'population']]

          ville  population
0         Paris     2133111
1     Marseille      873076
2          Lyon      522969
3      Toulouse      498003
4          Nice      342669
5        Nantes      323204
6   Montpellier      299096
7    Strasbourg      291313
8      Bordeaux      259809
9         Lille      236234
10       Rennes      222485
11        Reims      181194
12     Le Havre      165830
13        Rouen      114083
14         Caen      105354

In [26]:
## 4
print(df.iloc[1], "\n\n")
print(df.loc[0, "ville"])

ville                          Marseille
population                        873076
superficie                         240.6
region        Provence-Alpes-Côte d'Azur
densite                      3628.744805
Name: 1, dtype: object


Paris

In [16]:
## 5
df_pop = df[df["population"] > 200000] # Enlever le 1er df[] pour avoir la liste de True/False
df_pop

          ville  population  superficie                      region
0         Paris     2133111       105.4               Île-de-France
1     Marseille      873076       240.6  Provence-Alpes-Côte d'Azur
2          Lyon      522969        47.9        Auvergne-Rhône-Alpes
3      Toulouse      498003       118.3                   Occitanie
4          Nice      342669        71.9  Provence-Alpes-Côte d'Azur
5        Nantes      323204        65.2            Pays de la Loire
6   Montpellier      299096        56.9                   Occitanie
7    Strasbourg      291313        78.3                   Grand Est
8      Bordeaux      259809        49.4          Nouvelle-Aquitaine
9         Lille      236234        34.8             Hauts-de-France
10       Rennes      222485        50.4                    Bretagne

In [17]:
## 6
df_norm = df[(df["population"] > 100000) & (df["region"] == "Normandie")]
df_norm

       ville  population  superficie     region
12  Le Havre      165830        46.9  Normandie
13     Rouen      114083        21.4  Normandie
14      Caen      105354        25.7  Normandie

In [18]:
## 7
df_sorted = df.sort_values("population", ascending=False)
df_sorted

          ville  population  superficie                      region
0         Paris     2133111       105.4               Île-de-France
1     Marseille      873076       240.6  Provence-Alpes-Côte d'Azur
2          Lyon      522969        47.9        Auvergne-Rhône-Alpes
3      Toulouse      498003       118.3                   Occitanie
4          Nice      342669        71.9  Provence-Alpes-Côte d'Azur
5        Nantes      323204        65.2            Pays de la Loire
6   Montpellier      299096        56.9                   Occitanie
7    Strasbourg      291313        78.3                   Grand Est
8      Bordeaux      259809        49.4          Nouvelle-Aquitaine
9         Lille      236234        34.8             Hauts-de-France
10       Rennes      222485        50.4                    Bretagne
11        Reims      181194        46.9                   Grand Est
12     Le Havre      165830        46.9                   Normandie
13        Rouen      114083        21.4                   Normandie
14         Caen      105354        25.7                   Normandie

In [19]:
## 8
df["densite"] = df["population"] / df["superficie"]
df.sort_values("densite", ascending=False)
df

,ville,population,superficie,region,densite
0,Paris,2133111,105.4,Île-de-France,20238.244782
1,Marseille,873076,240.6,Provence-Alpes-Côte d'Azur,3628.744805
2,Lyon,522969,47.9,Auvergne-Rhône-Alpes,10917.933194
3,Toulouse,498003,118.3,Occitanie,4209.661877
4,Nice,342669,71.9,Provence-Alpes-Côte d'Azur,4765.910987
5,Nantes,323204,65.2,Pays de la Loire,4957.116564
6,Montpellier,299096,56.9,Occitanie,5256.520211
7,Strasbourg,291313,78.3,Grand Est,3720.472542
8,Bordeaux,259809,49.4,Nouvelle-Aquitaine,5259.291498
9,Lille,236234,34.8,Hauts-de-France,6788.333333
10,Rennes,222485,50.4,Bretagne,4414.384921
11,Reims,181194,46.9,Grand Est,3863.411514
12,Le Havre,165830,46.9,Normandie,3535.820896
13,Rouen,114083,21.4,Normandie,5330.981308
14,Caen,105354,25.7,Normandie,4099.377432

In [20]:
## 9 (réflexion en commentaire)
# Loc : permet de ressortir les data en suivant l'index et le nom d'une ou des colonne(s) souhaitée(s)
# iLoc : permet de ressortir les datas avec une liste d'index et numéro de ligne et colonnes