# Pandas — sélection & filtrage avancés (cours)

Cellules d'exemple à **exécuter** (contexte : table de salariés). Les exercices (contexte : des commandes) sont tout en bas.

### Le df d'exemple

In [1]:
import pandas as pd
df = pd.DataFrame({
    "nom": ["Alice", "Bob", "Chloé"],
    "salaire": [38000, 41000, 45000],
    "service": ["Data", "Data", "RH"],
})
df

     nom  salaire service
0  Alice    38000    Data
1    Bob    41000    Data
2  Chloé    45000      RH

### value_counts — compter les occurrences

In [2]:
df["service"].value_counts()            # combien de fois chaque service apparaît

service
Data    2
RH      1
Name: count, dtype: int64

### isin — filtrer sur une liste de valeurs

In [3]:
df[df["service"].isin(["Data", "RH"])]  # au lieu de combiner des | (ou)

     nom  salaire service
0  Alice    38000    Data
1    Bob    41000    Data
2  Chloé    45000      RH

### between — filtrer sur un intervalle (bornes incluses)

In [4]:
df[df["salaire"].between(39000, 42000)] # salaires entre 39000 et 42000 inclus

   nom  salaire service
1  Bob    41000    Data

### nlargest / nsmallest — top N direct

In [5]:
df.nlargest(2, "salaire")               # les 2 plus gros salaires (tri + head en un appel)

     nom  salaire service
2  Chloé    45000      RH
1    Bob    41000    Data

### .str — méthodes texte sur toute la colonne

In [18]:
print(df["nom"].str.upper().tolist())   # tout en majuscules
df[df["nom"].str.contains("o", case=False)]   # noms contenant "o" (casse ignorée)

['ALICE', 'BOB', 'CHLOÉ']

     nom  salaire service
1    Bob    41000    Data
2  Chloé    45000      RH

### Enchaîner filtre -> tri -> sélection

In [ ]:
(
    df[df["service"] == "Data"]               # 1) filtre
      .sort_values("salaire", ascending=False) # 2) tri
      [["nom", "salaire"]]                     # 3) colonnes
)

     nom  salaire
1    Bob    41000
0  Alice    38000

# Exercices

Dataset : `data/commandes.csv` (commandes e-commerce). Écris ton code sous chaque énoncé.

1. Charge `data/commandes.csv` dans `cmd` ; `head()` et `info()`. Combien de commandes, des valeurs manquantes ?
2. `value_counts` : nombre de commandes par `categorie`, puis par `ville`. Catégorie la plus fréquente ?
3. Colonne calculée `montant` = `quantite` × `prix_unitaire`.
4. `nlargest` : les **5** plus gros `montant` (colonnes `client`, `produit`, `montant`).
5. `isin` : commandes des catégories `"Informatique"` et `"Mobilier"`.
6. `between` : commandes dont `prix_unitaire` est entre **50 et 200** inclus.
7. `.str` : commandes dont le `produit` contient `"Clavier"` (casse ignorée). Bonus : `client` en majuscules.
8. Enchaînement : catégorie `"Informatique"` ET `montant` > 300, tri `montant` décroissant, colonnes `client`, `produit`, `montant`.
9. Réflexion (pas de code) : à quoi sert `value_counts` ? Pourquoi `isin([...])` plutôt que plusieurs `|` ?

In [ ]:
## 1
import pandas as pd

df = pd.read_csv("data/commandes.csv")

print(df)
print(df.describe(), "\n")
print(df.head(5), "\n")
print(df.tail(5))

# Il y a en tout 24 commandes et 0 valeurs manquantes d'après df

   id_commande        date   client     categorie                  produit  \
0         C001  2026-01-05   Durand  Informatique      Ordinateur portable
1         C002  2026-01-07  Lefevre   Bureautique        Ramette papier A4
2         C003  2026-01-09   Moreau  Informatique        Clavier mécanique
3         C004  2026-01-12   Durand   Accessoires          Souris sans fil
4         C005  2026-01-15    Petit      Mobilier         Chaise de bureau
5         C006  2026-01-18  Garnier  Informatique          Écran 27 pouces
6         C007  2026-01-20   Moreau   Bureautique       Stylos (lot de 50)
7         C008  2026-01-22  Lefevre  Informatique           Disque SSD 1To
8         C009  2026-01-25    Petit      Mobilier          Bureau réglable
9         C010  2026-01-28  Roussel   Accessoires             Casque audio
10        C011  2026-02-02   Durand  Informatique         Clavier sans fil
11        C012  2026-02-04  Garnier      Mobilier        Caisson à tiroirs
12        C013  2026-02-06   Moreau  Informatique      Ordinateur portable
13        C014  2026-02-09  Roussel   Bureautique    Classeurs (lot de 10)
14        C015  2026-02-11    Petit   Accessoires          Tapis de souris
15        C016  2026-02-14  Lefevre  Informatique          Écran 24 pouces
16        C017  2026-02-16  Garnier      Mobilier         Chaise de bureau
17        C018  2026-02-19   Durand  Informatique                Webcam HD
18        C019  2026-02-21  Roussel  Informatique        Clavier mécanique
19        C020  2026-02-24   Moreau   Accessoires               Câble HDMI
20        C021  2026-02-26    Petit  Informatique  Station d'accueil USB-C
21        C022  2026-03-01  Garnier   Bureautique                Agrafeuse
22        C023  2026-03-03  Lefevre      Mobilier      Lampe de bureau LED
23        C024  2026-03-05   Durand  Informatique      Ordinateur portable

    quantite  prix_unitaire     ville
0          1          899.0     Rouen
1         10            4.5      Caen
2          2           79.9  Le Havre
3          3           24.9     Rouen
4          1          189.0     Paris
5          2          229.0     Lille
6          5           12.0  Le Havre
7          4           89.9      Caen
8          1          349.0     Paris
9          2           59.9    Nantes
10         1           45.0     Rouen
11         2          119.0     Lille
12         1         1099.0  Le Havre
13         6            8.5    Nantes
14         4            9.9     Paris
15         3          149.0      Caen
16         2          189.0     Lille
17         1           69.9     Rouen
18         1           79.9    Nantes
19         5           11.9  Le Havre
20         2          159.0     Paris
21         3           14.9     Lille
22         2           39.9      Caen
23         2          949.0     Rouen
        quantite  prix_unitaire
count  24.000000      24.000000
mean    2.750000     203.375000
std     2.111048     313.848193
min     1.000000       4.500000
25%     1.000000      22.400000
50%     2.000000      79.900000
75%     3.250000     189.000000
max    10.000000    1099.000000

  id_commande        date   client     categorie              produit  \
0        C001  2026-01-05   Durand  Informatique  Ordinateur portable
1        C002  2026-01-07  Lefevre   Bureautique    Ramette papier A4
2        C003  2026-01-09   Moreau  Informatique    Clavier mécanique
3        C004  2026-01-12   Durand   Accessoires      Souris sans fil
4        C005  2026-01-15    Petit      Mobilier     Chaise de bureau

   quantite  prix_unitaire     ville
0         1          899.0     Rouen
1        10            4.5      Caen
2         2           79.9  Le Havre
3         3           24.9     Rouen
4         1          189.0     Paris

   id_commande        date   client     categorie                  produit  \
19        C020  2026-02-24   Moreau   Accessoires               Câble HDMI
20        C021  2026-02-26    Petit  Informatique  Station d'accueil USB-C
21        C022  2026-03-01  Garnier   Bureautique                Agrafeuse
22        C023  2026-03-03  Lefevre      Mobilier      Lampe de bureau LED
23        C024  2026-03-05   Durand  Informatique      Ordinateur portable

    quantite  prix_unitaire     ville
19         5           11.9  Le Havre
20         2          159.0     Paris
21         3           14.9     Lille
22         2           39.9      Caen
23         2          949.0     Rouen

In [74]:
## 2
df[["categorie", "ville"]].value_counts()

categorie     ville
Informatique  Rouen       4
              Le Havre    2
Mobilier      Paris       2
Informatique  Caen        2
Mobilier      Lille       2
Bureautique   Caen        1
Accessoires   Rouen       1
Informatique  Lille       1
Bureautique   Le Havre    1
Accessoires   Nantes      1
Bureautique   Nantes      1
Accessoires   Paris       1
Informatique  Nantes      1
Accessoires   Le Havre    1
Informatique  Paris       1
Bureautique   Lille       1
Mobilier      Caen        1
Name: count, dtype: int64

In [40]:
## 3
df["montant"] = df["quantite"] * df["prix_unitaire"]
df

,id_commande,date,client,categorie,produit,quantite,prix_unitaire,ville,montant
0,C001,2026-01-05,Durand,Informatique,Ordinateur portable,1,899.0,Rouen,899.0
1,C002,2026-01-07,Lefevre,Bureautique,Ramette papier A4,10,4.5,Caen,45.0
2,C003,2026-01-09,Moreau,Informatique,Clavier mécanique,2,79.9,Le Havre,159.8
3,C004,2026-01-12,Durand,Accessoires,Souris sans fil,3,24.9,Rouen,74.7
4,C005,2026-01-15,Petit,Mobilier,Chaise de bureau,1,189.0,Paris,189.0
5,C006,2026-01-18,Garnier,Informatique,Écran 27 pouces,2,229.0,Lille,458.0
6,C007,2026-01-20,Moreau,Bureautique,Stylos (lot de 50),5,12.0,Le Havre,60.0
7,C008,2026-01-22,Lefevre,Informatique,Disque SSD 1To,4,89.9,Caen,359.6
8,C009,2026-01-25,Petit,Mobilier,Bureau réglable,1,349.0,Paris,349.0
9,C010,2026-01-28,Roussel,Accessoires,Casque audio,2,59.9,Nantes,119.8
10,C011,2026-02-02,Durand,Informatique,Clavier sans fil,1,45.0,Rouen,45.0
11,C012,2026-02-04,Garnier,Mobilier,Caisson à tiroirs,2,119.0,Lille,238.0
12,C013,2026-02-06,Moreau,Informatique,Ordinateur portable,1,1099.0,Le Havre,1099.0
13,C014,2026-02-09,Roussel,Bureautique,Classeurs (lot de 10),6,8.5,Nantes,51.0
14,C015,2026-02-11,Petit,Accessoires,Tapis de souris,4,9.9,Paris,39.6
15,C016,2026-02-14,Lefevre,Informatique,Écran 24 pouces,3,149.0,Caen,447.0
16,C017,2026-02-16,Garnier,Mobilier,Chaise de bureau,2,189.0,Lille,378.0
17,C018,2026-02-19,Durand,Informatique,Webcam HD,1,69.9,Rouen,69.9
18,C019,2026-02-21,Roussel,Informatique,Clavier mécanique,1,79.9,Nantes,79.9
19,C020,2026-02-24,Moreau,Accessoires,Câble HDMI,5,11.9,Le Havre,59.5
20,C021,2026-02-26,Petit,Informatique,Station d'accueil USB-C,2,159.0,Paris,318.0
21,C022,2026-03-01,Garnier,Bureautique,Agrafeuse,3,14.9,Lille,44.7
22,C023,2026-03-03,Lefevre,Mobilier,Lampe de bureau LED,2,39.9,Caen,79.8
23,C024,2026-03-05,Durand,Informatique,Ordinateur portable,2,949.0,Rouen,1898.0

In [44]:
## 4
df[["client", "produit", "montant"]].nlargest(5, "montant").sort_values("montant")

     client              produit  montant
15  Lefevre      Écran 24 pouces    447.0
5   Garnier      Écran 27 pouces    458.0
0    Durand  Ordinateur portable    899.0
12   Moreau  Ordinateur portable   1099.0
23   Durand  Ordinateur portable   1898.0

In [49]:
## 5
df[df["categorie"].isin(["Informatique", "Mobilier"])].sort_values("categorie")

,id_commande,date,client,categorie,produit,quantite,prix_unitaire,ville,montant
0,C001,2026-01-05,Durand,Informatique,Ordinateur portable,1,899.0,Rouen,899.0
2,C003,2026-01-09,Moreau,Informatique,Clavier mécanique,2,79.9,Le Havre,159.8
5,C006,2026-01-18,Garnier,Informatique,Écran 27 pouces,2,229.0,Lille,458.0
7,C008,2026-01-22,Lefevre,Informatique,Disque SSD 1To,4,89.9,Caen,359.6
10,C011,2026-02-02,Durand,Informatique,Clavier sans fil,1,45.0,Rouen,45.0
12,C013,2026-02-06,Moreau,Informatique,Ordinateur portable,1,1099.0,Le Havre,1099.0
15,C016,2026-02-14,Lefevre,Informatique,Écran 24 pouces,3,149.0,Caen,447.0
17,C018,2026-02-19,Durand,Informatique,Webcam HD,1,69.9,Rouen,69.9
18,C019,2026-02-21,Roussel,Informatique,Clavier mécanique,1,79.9,Nantes,79.9
20,C021,2026-02-26,Petit,Informatique,Station d'accueil USB-C,2,159.0,Paris,318.0
23,C024,2026-03-05,Durand,Informatique,Ordinateur portable,2,949.0,Rouen,1898.0
4,C005,2026-01-15,Petit,Mobilier,Chaise de bureau,1,189.0,Paris,189.0
8,C009,2026-01-25,Petit,Mobilier,Bureau réglable,1,349.0,Paris,349.0
11,C012,2026-02-04,Garnier,Mobilier,Caisson à tiroirs,2,119.0,Lille,238.0
16,C017,2026-02-16,Garnier,Mobilier,Chaise de bureau,2,189.0,Lille,378.0
22,C023,2026-03-03,Lefevre,Mobilier,Lampe de bureau LED,2,39.9,Caen,79.8

In [50]:
## 6
df[df["prix_unitaire"].between(50, 200, inclusive="both")]

,id_commande,date,client,categorie,produit,quantite,prix_unitaire,ville,montant
2,C003,2026-01-09,Moreau,Informatique,Clavier mécanique,2,79.9,Le Havre,159.8
4,C005,2026-01-15,Petit,Mobilier,Chaise de bureau,1,189.0,Paris,189.0
7,C008,2026-01-22,Lefevre,Informatique,Disque SSD 1To,4,89.9,Caen,359.6
9,C010,2026-01-28,Roussel,Accessoires,Casque audio,2,59.9,Nantes,119.8
11,C012,2026-02-04,Garnier,Mobilier,Caisson à tiroirs,2,119.0,Lille,238.0
15,C016,2026-02-14,Lefevre,Informatique,Écran 24 pouces,3,149.0,Caen,447.0
16,C017,2026-02-16,Garnier,Mobilier,Chaise de bureau,2,189.0,Lille,378.0
17,C018,2026-02-19,Durand,Informatique,Webcam HD,1,69.9,Rouen,69.9
18,C019,2026-02-21,Roussel,Informatique,Clavier mécanique,1,79.9,Nantes,79.9
20,C021,2026-02-26,Petit,Informatique,Station d'accueil USB-C,2,159.0,Paris,318.0

In [81]:
## 7
client_uppper_list = df["client"].str.upper().to_list()
df_clavier = df[df["produit"].str.contains("Clavier", case=False)]

df_clavier

,id_commande,date,client,categorie,produit,quantite,prix_unitaire,ville,montant
2,C003,2026-01-09,Moreau,Informatique,Clavier mécanique,2,79.9,Le Havre,159.8
10,C011,2026-02-02,Durand,Informatique,Clavier sans fil,1,45.0,Rouen,45.0
18,C019,2026-02-21,Roussel,Informatique,Clavier mécanique,1,79.9,Nantes,79.9

In [72]:
## 8 
(
    df[(df["montant"] > 300) & (df["categorie"] == "Informatique")]
    .sort_values("montant", ascending=False)
    [["client", "produit", "montant"]]
    
)

     client                  produit  montant
23   Durand      Ordinateur portable   1898.0
12   Moreau      Ordinateur portable   1099.0
0    Durand      Ordinateur portable    899.0
5   Garnier          Écran 27 pouces    458.0
15  Lefevre          Écran 24 pouces    447.0
7   Lefevre           Disque SSD 1To    359.6
20    Petit  Station d'accueil USB-C    318.0

In [ ]:
## 9 (réflexion en commentaire)
# value_counts : permet de compter le nombre d'occurence des valeurs d'une ou plusieurs colonnes (ex : compter le nombre de personne par prénom par ville) 
# isin : comme le IN en SQl ça permet de de sélectionner plusieurs valeurs à filtrer plutôt que de devoir écrire plusieurs lignes pour spécifier ce qu'on souhaite (évite la répétition et la surcharge du code)