# Combiner des DataFrames : merge & concat (cours)

Exemples à **exécuter** (contexte : commandes + clients). Les exercices (commandes web) sont tout en bas.

### Deux tables à joindre

In [37]:
import pandas as pd
commandes = pd.DataFrame({"id_commande":[1,2,3],"id_client":[10,11,10],"montant":[100,250,80]})
clients   = pd.DataFrame({"id_client":[10,11,12],"nom":["Alice","Bob","Chloé"],"ville":["Rouen","Paris","Lyon"]})
display(commandes)
display(clients)

   id_commande  id_client  montant
0            1         10      100
1            2         11      250
2            3         10       80

   id_client    nom  ville
0         10  Alice  Rouen
1         11    Bob  Paris
2         12  Chloé   Lyon

### merge (le JOIN de pandas) + les how

In [42]:
print("inner (défaut) :")
display(pd.merge(commandes, clients, on="id_client"))
print("left (garde toutes les commandes) :") 
display(pd.merge(clients, commandes, on="id_client", how="left"))

inner (défaut) :

   id_commande  id_client  montant    nom  ville
0            1         10      100  Alice  Rouen
1            2         11      250    Bob  Paris
2            3         10       80  Alice  Rouen

left (garde toutes les commandes) :

   id_client    nom  ville  id_commande  montant
0         10  Alice  Rouen          1.0    100.0
1         10  Alice  Rouen          3.0     80.0
2         11    Bob  Paris          2.0    250.0
3         12  Chloé   Lyon          NaN      NaN

### Piège : inner peut perdre des lignes -> comparer les tailles

In [26]:
fusion = pd.merge(commandes, clients, on="id_client")   # inner
print("commandes de départ :", len(commandes), "| après jointure :", len(fusion))

commandes de départ : 3 | après jointure : 3

### concat : empiler

In [27]:
jan = pd.DataFrame({"produit":["A","B"],"qte":[10,5]})
fev = pd.DataFrame({"produit":["A","C"],"qte":[7,3]})
print(pd.concat([jan, fev], ignore_index=True))

  produit  qte
0       A   10
1       B    5
2       A    7
3       C    3

# Exercices

**Trois jeux de données, chargés dans la cellule ci-dessous :**
- `commandes_web` — les commandes du **mois 1** (une ligne = une commande, avec `client_id`, `montant`).
- `clients_web` — le **catalogue des clients connus** (`client_id`, nom, `segment`, `ville`).
- `commandes_web_mois2` — les commandes du **mois 2** (même structure que le mois 1). **Ne sert qu'à la question 5.**

**À toi de choisir tes outils.**

1. **Joins** les commandes du **mois 1** (`commandes_web`) avec `clients_web`, pour ajouter à chaque commande le **segment** et la **ville** du client. Combien de lignes obtiens-tu ?
2. Combien de commandes dans `commandes_web` au départ ? Compare avec la question 1 : la jointure a-t-elle **perdu des commandes** ? Pourquoi ? Refais-la pour **garder les 60 commandes du mois 1**, même les « invité » (`client_id` absent de `clients_web`).
3. Sur ce tableau complet, calcule le **CA par segment**. Que fais-tu des commandes « invité » sans segment ?
4. Toujours sur ce tableau complet, calcule le **CA par ville**, du plus élevé au plus faible.
5. **Sans le catalogue clients** : mets bout à bout `commandes_web` (mois 1) et `commandes_web_mois2` (mois 2), puis calcule le **CA total des deux mois**. (empiler n'est pas une jointure)
6. Réflexion (pas de code) : différence entre une jointure `inner` et une jointure `left`, et quand choisir l'une plutôt que l'autre ?

In [28]:
# --- CELLULE FOURNIE : données chargées pour toi ---
import pandas as pd
commandes_web       = pd.read_csv("data/commandes_web.csv")       # mois 1
clients_web         = pd.read_csv("data/clients_web.csv")          # catalogue clients
commandes_web_mois2 = pd.read_csv("data/commandes_web_mois2.csv")  # mois 2 (question 5 uniquement)
print("commandes_web (mois 1):", commandes_web.shape, "| clients_web:", clients_web.shape, "| mois2:", commandes_web_mois2.shape)

commandes_web (mois 1): (60, 5) | clients_web: (15, 4) | mois2: (30, 5)

In [ ]:
## 1 & 2
print("Affichage de la table client :")
display(clients_web, len(clients_web))
print("Affichage de la table commandes :")
display(commandes_web, len(commandes_web))

# Avec INNER JOIN
print("Affichage du merge de commandes et clients (INNER) :")
df_inner = pd.merge(commandes_web, clients_web, on="client_id")
print("Nombre de lignes dans la table (INNER) : ", len(df_inner))
display(df_inner)

# Avec LEFT JOIN
print("Affichage du merge de commandes et clients (LEFT) :")
df_left = pd.merge(commandes_web, clients_web, on="client_id", how="left")
print("Nombre de lignes dans la table (LEFT) : ", len(df_left))
display(df_left)

# On a 15 lignes dans clients et 60 dans commandes (mois 1).
# D'après l'affichage on perd 13 lignes et ce qui est normal car on a dans commandes des client_id > 15 donc pas de correspondances, donc n'apparaissent pas
# Avec un LEFT on ne perd rien mais les clients_id qui ne sont pas dans clients auront des valeurs NaN pour nom, segment et ville

Affichage de la table client :

    client_id       nom      segment   ville
0           1  Client01          Pro  Nantes
1           2  Client02      Premium   Rouen
2           3  Client03  Particulier   Lille
3           4  Client04  Particulier    Lyon
4           5  Client05  Particulier   Paris
5           6  Client06  Particulier  Nantes
6           7  Client07  Particulier   Rouen
7           8  Client08  Particulier  Nantes
8           9  Client09      Premium    Lyon
9          10  Client10      Premium   Lille
10         11  Client11      Premium   Lille
11         12  Client12      Premium    Lyon
12         13  Client13          Pro   Rouen
13         14  Client14          Pro    Lyon
14         15  Client15      Premium   Paris

15

Affichage de la table commandes :

   commande_id        date  client_id  montant canal
0        C0001  2026-01-09        901   241.62   app
1        C0002  2026-01-13        904    28.48   web
2        C0003  2026-01-05         15    88.37   app
3        C0004  2026-01-22         13    33.94   tel
4        C0005  2026-01-23          1   299.36   tel
5        C0006  2026-01-27         13   141.53   app
6        C0007  2026-01-05         10   323.76   web
7        C0008  2026-01-12         13   298.60   tel
8        C0009  2026-01-09         14   298.98   web
9        C0010  2026-01-20        900   238.31   tel
10       C0011  2026-01-12          5   397.95   tel
11       C0012  2026-01-04          2   153.96   web
12       C0013  2026-01-25          1   399.58   web
13       C0014  2026-01-06          8    62.16   tel
14       C0015  2026-01-10          1   253.56   tel
15       C0016  2026-01-09        901    17.59   web
16       C0017  2026-01-28         11   276.12   web
17       C0018  2026-01-17          5   389.83   tel
18       C0019  2026-01-10         13   202.75   app
19       C0020  2026-01-15          7   131.33   web
20       C0021  2026-01-22          3   378.24   web
21       C0022  2026-01-12        907   167.44   app
22       C0023  2026-01-18        902   122.26   tel
23       C0024  2026-01-08          4    28.35   tel
24       C0025  2026-01-14          9   119.61   tel
25       C0026  2026-01-08        907   111.28   tel
26       C0027  2026-01-11          2   137.86   app
27       C0028  2026-01-13        900    45.40   tel
28       C0029  2026-01-19         13   169.96   tel
29       C0030  2026-01-08         11   210.43   web
30       C0031  2026-01-01          3   298.28   app
31       C0032  2026-01-20          9   283.42   web
32       C0033  2026-01-04          9    21.02   web
33       C0034  2026-01-10          9    34.70   app
34       C0035  2026-01-23        902   276.36   web
35       C0036  2026-01-21         10   375.78   tel
36       C0037  2026-01-07          1    28.16   web
37       C0038  2026-01-18          3    43.98   web
38       C0039  2026-01-14         15   317.83   tel
39       C0040  2026-01-12         15   160.47   web
40       C0041  2026-01-25          3   130.33   app
41       C0042  2026-01-06          3   269.09   app
42       C0043  2026-01-16          8   366.75   app
43       C0044  2026-01-15          5   280.16   app
44       C0045  2026-01-26          8   191.18   tel
45       C0046  2026-01-08          4   111.93   app
46       C0047  2026-01-02         13    82.05   app
47       C0048  2026-01-09          7   132.87   tel
48       C0049  2026-01-08          7    52.47   tel
49       C0050  2026-01-07          3   312.78   tel
50       C0051  2026-01-11         11   288.53   app
51       C0052  2026-01-02          1   235.54   app
52       C0053  2026-01-11          4   306.87   tel
53       C0054  2026-01-26        905    80.07   tel
54       C0055  2026-01-13         12    43.11   web
55       C0056  2026-01-08          5    38.85   tel
56       C0057  2026-01-02        901   385.67   web
57       C0058  2026-01-21        908   145.73   app
58       C0059  2026-01-08        908   142.78   tel
59       C0060  2026-01-13          1    32.12   web

60

Affichage du merge de commandes et clients (INNER) :
Nombre de lignes dans la table (INNER) :  47

,commande_id,date,client_id,montant,canal,nom,segment,ville
0,C0003,2026-01-05,15,88.37,app,Client15,Premium,Paris
1,C0004,2026-01-22,13,33.94,tel,Client13,Pro,Rouen
2,C0005,2026-01-23,1,299.36,tel,Client01,Pro,Nantes
3,C0006,2026-01-27,13,141.53,app,Client13,Pro,Rouen
4,C0007,2026-01-05,10,323.76,web,Client10,Premium,Lille
5,C0008,2026-01-12,13,298.60,tel,Client13,Pro,Rouen
6,C0009,2026-01-09,14,298.98,web,Client14,Pro,Lyon
7,C0011,2026-01-12,5,397.95,tel,Client05,Particulier,Paris
8,C0012,2026-01-04,2,153.96,web,Client02,Premium,Rouen
9,C0013,2026-01-25,1,399.58,web,Client01,Pro,Nantes
10,C0014,2026-01-06,8,62.16,tel,Client08,Particulier,Nantes
11,C0015,2026-01-10,1,253.56,tel,Client01,Pro,Nantes
12,C0017,2026-01-28,11,276.12,web,Client11,Premium,Lille
13,C0018,2026-01-17,5,389.83,tel,Client05,Particulier,Paris
14,C0019,2026-01-10,13,202.75,app,Client13,Pro,Rouen
15,C0020,2026-01-15,7,131.33,web,Client07,Particulier,Rouen
16,C0021,2026-01-22,3,378.24,web,Client03,Particulier,Lille
17,C0024,2026-01-08,4,28.35,tel,Client04,Particulier,Lyon
18,C0025,2026-01-14,9,119.61,tel,Client09,Premium,Lyon
19,C0027,2026-01-11,2,137.86,app,Client02,Premium,Rouen
20,C0029,2026-01-19,13,169.96,tel,Client13,Pro,Rouen
21,C0030,2026-01-08,11,210.43,web,Client11,Premium,Lille
22,C0031,2026-01-01,3,298.28,app,Client03,Particulier,Lille
23,C0032,2026-01-20,9,283.42,web,Client09,Premium,Lyon
24,C0033,2026-01-04,9,21.02,web,Client09,Premium,Lyon
25,C0034,2026-01-10,9,34.70,app,Client09,Premium,Lyon
26,C0036,2026-01-21,10,375.78,tel,Client10,Premium,Lille
27,C0037,2026-01-07,1,28.16,web,Client01,Pro,Nantes
28,C0038,2026-01-18,3,43.98,web,Client03,Particulier,Lille
29,C0039,2026-01-14,15,317.83,tel,Client15,Premium,Paris
30,C0040,2026-01-12,15,160.47,web,Client15,Premium,Paris
31,C0041,2026-01-25,3,130.33,app,Client03,Particulier,Lille
32,C0042,2026-01-06,3,269.09,app,Client03,Particulier,Lille
33,C0043,2026-01-16,8,366.75,app,Client08,Particulier,Nantes
34,C0044,2026-01-15,5,280.16,app,Client05,Particulier,Paris
35,C0045,2026-01-26,8,191.18,tel,Client08,Particulier,Nantes
36,C0046,2026-01-08,4,111.93,app,Client04,Particulier,Lyon
37,C0047,2026-01-02,13,82.05,app,Client13,Pro,Rouen
38,C0048,2026-01-09,7,132.87,tel,Client07,Particulier,Rouen
39,C0049,2026-01-08,7,52.47,tel,Client07,Particulier,Rouen
40,C0050,2026-01-07,3,312.78,tel,Client03,Particulier,Lille
41,C0051,2026-01-11,11,288.53,app,Client11,Premium,Lille
42,C0052,2026-01-02,1,235.54,app,Client01,Pro,Nantes
43,C0053,2026-01-11,4,306.87,tel,Client04,Particulier,Lyon
44,C0055,2026-01-13,12,43.11,web,Client12,Premium,Lyon
45,C0056,2026-01-08,5,38.85,tel,Client05,Particulier,Paris
46,C0060,2026-01-13,1,32.12,web,Client01,Pro,Nantes

Affichage du merge de commandes et clients (LEFT) :
Nombre de lignes dans la table (LEFT) :  60

,commande_id,date,client_id,montant,canal,nom,segment,ville
0,C0001,2026-01-09,901,241.62,app,NaN,NaN,NaN
1,C0002,2026-01-13,904,28.48,web,NaN,NaN,NaN
2,C0003,2026-01-05,15,88.37,app,Client15,Premium,Paris
3,C0004,2026-01-22,13,33.94,tel,Client13,Pro,Rouen
4,C0005,2026-01-23,1,299.36,tel,Client01,Pro,Nantes
5,C0006,2026-01-27,13,141.53,app,Client13,Pro,Rouen
6,C0007,2026-01-05,10,323.76,web,Client10,Premium,Lille
7,C0008,2026-01-12,13,298.60,tel,Client13,Pro,Rouen
8,C0009,2026-01-09,14,298.98,web,Client14,Pro,Lyon
9,C0010,2026-01-20,900,238.31,tel,NaN,NaN,NaN
10,C0011,2026-01-12,5,397.95,tel,Client05,Particulier,Paris
11,C0012,2026-01-04,2,153.96,web,Client02,Premium,Rouen
12,C0013,2026-01-25,1,399.58,web,Client01,Pro,Nantes
13,C0014,2026-01-06,8,62.16,tel,Client08,Particulier,Nantes
14,C0015,2026-01-10,1,253.56,tel,Client01,Pro,Nantes
15,C0016,2026-01-09,901,17.59,web,NaN,NaN,NaN
16,C0017,2026-01-28,11,276.12,web,Client11,Premium,Lille
17,C0018,2026-01-17,5,389.83,tel,Client05,Particulier,Paris
18,C0019,2026-01-10,13,202.75,app,Client13,Pro,Rouen
19,C0020,2026-01-15,7,131.33,web,Client07,Particulier,Rouen
20,C0021,2026-01-22,3,378.24,web,Client03,Particulier,Lille
21,C0022,2026-01-12,907,167.44,app,NaN,NaN,NaN
22,C0023,2026-01-18,902,122.26,tel,NaN,NaN,NaN
23,C0024,2026-01-08,4,28.35,tel,Client04,Particulier,Lyon
24,C0025,2026-01-14,9,119.61,tel,Client09,Premium,Lyon
25,C0026,2026-01-08,907,111.28,tel,NaN,NaN,NaN
26,C0027,2026-01-11,2,137.86,app,Client02,Premium,Rouen
27,C0028,2026-01-13,900,45.40,tel,NaN,NaN,NaN
28,C0029,2026-01-19,13,169.96,tel,Client13,Pro,Rouen
29,C0030,2026-01-08,11,210.43,web,Client11,Premium,Lille
30,C0031,2026-01-01,3,298.28,app,Client03,Particulier,Lille
31,C0032,2026-01-20,9,283.42,web,Client09,Premium,Lyon
32,C0033,2026-01-04,9,21.02,web,Client09,Premium,Lyon
33,C0034,2026-01-10,9,34.70,app,Client09,Premium,Lyon
34,C0035,2026-01-23,902,276.36,web,NaN,NaN,NaN
35,C0036,2026-01-21,10,375.78,tel,Client10,Premium,Lille
36,C0037,2026-01-07,1,28.16,web,Client01,Pro,Nantes
37,C0038,2026-01-18,3,43.98,web,Client03,Particulier,Lille
38,C0039,2026-01-14,15,317.83,tel,Client15,Premium,Paris
39,C0040,2026-01-12,15,160.47,web,Client15,Premium,Paris
40,C0041,2026-01-25,3,130.33,app,Client03,Particulier,Lille
41,C0042,2026-01-06,3,269.09,app,Client03,Particulier,Lille
42,C0043,2026-01-16,8,366.75,app,Client08,Particulier,Nantes
43,C0044,2026-01-15,5,280.16,app,Client05,Particulier,Paris
44,C0045,2026-01-26,8,191.18,tel,Client08,Particulier,Nantes
45,C0046,2026-01-08,4,111.93,app,Client04,Particulier,Lyon
46,C0047,2026-01-02,13,82.05,app,Client13,Pro,Rouen
47,C0048,2026-01-09,7,132.87,tel,Client07,Particulier,Rouen
48,C0049,2026-01-08,7,52.47,tel,Client07,Particulier,Rouen
49,C0050,2026-01-07,3,312.78,tel,Client03,Particulier,Lille
50,C0051,2026-01-11,11,288.53,app,Client11,Premium,Lille
51,C0052,2026-01-02,1,235.54,app,Client01,Pro,Nantes
52,C0053,2026-01-11,4,306.87,tel,Client04,Particulier,Lyon
53,C0054,2026-01-26,905,80.07,tel,NaN,NaN,NaN
54,C0055,2026-01-13,12,43.11,web,Client12,Premium,Lyon
55,C0056,2026-01-08,5,38.85,tel,Client05,Particulier,Paris
56,C0057,2026-01-02,901,385.67,web,NaN,NaN,NaN
57,C0058,2026-01-21,908,145.73,app,NaN,NaN,NaN
58,C0059,2026-01-08,908,142.78,tel,NaN,NaN,NaN
59,C0060,2026-01-13,1,32.12,web,Client01,Pro,Nantes

In [ ]:
## 3
CA_segment = df_left.groupby("segment")["montant"].sum().sort_values(ascending=False).reset_index()
display(CA_segment)


CA_segment_2 = df_left.fillna("Inconnu").groupby("segment")["montant"].sum().sort_values(ascending=False).reset_index()
display(CA_segment_2)

# Comme on peut le voir dans le cas 1, je n'ai pas précisé dropna=False donc le groupby va drop les valeur NaN automatiquement.
# Si on laisse le dropna=false comme dans le cas 2 alors on aura aussi un segment NaN compris dans le df affiché.
# Comme pour pleins de cas ça dépend de ce qu'on veut en entreprise si ce qui nous intéresse c'est le CA total et les clients qui ne sont pas dans client_id sont quand même valides alors on garde la solution #2
# mais si on  veut seulement les CA des segments valides alors on prends la solution #1

       segment  montant
0  Particulier  3923.40
1      Premium  2834.97
2          Pro  2476.13

       segment  montant
0  Particulier  3923.40
1      Premium  2834.97
2          Pro  2476.13
3       Invité  2002.99

In [ ]:
## 4
CA_ville = df_left.groupby("ville")["montant"].sum().sort_values(ascending=False)
display(CA_ville.to_frame(name="CA total").reset_index())

CA_ville_2 = df_left.groupby("ville", dropna=False)["montant"].sum().sort_values(ascending=False)
display(CA_ville_2.to_frame(name="CA total").reset_index())

#Même raisonnement qu'à la question précédente

    ville  CA total
0   Lille   2907.32
1  Nantes   1868.41
2   Paris   1673.46
3   Rouen   1537.32
4    Lyon   1247.99

    ville  CA total
0   Lille   2907.32
1     NaN   2002.99
2  Nantes   1868.41
3   Paris   1673.46
4   Rouen   1537.32
5    Lyon   1247.99

In [75]:
## 5
print("Mois 1 de commandes : ")
display(commandes_web)

print("Mois 2 de commandes : ")
display(commandes_web_mois2)

all_commandes = pd.concat([commandes_web, commandes_web_mois2], ignore_index=True)
print("Mois 1 & 2 de commandes : ")
display(all_commandes)

# Calcul CA total :

ca_total = all_commandes["montant"].sum()
print(f"Le CA total sur 2 mois est de {ca_total}€")

Mois 1 de commandes :

   commande_id        date  client_id  montant canal
0        C0001  2026-01-09        901   241.62   app
1        C0002  2026-01-13        904    28.48   web
2        C0003  2026-01-05         15    88.37   app
3        C0004  2026-01-22         13    33.94   tel
4        C0005  2026-01-23          1   299.36   tel
5        C0006  2026-01-27         13   141.53   app
6        C0007  2026-01-05         10   323.76   web
7        C0008  2026-01-12         13   298.60   tel
8        C0009  2026-01-09         14   298.98   web
9        C0010  2026-01-20        900   238.31   tel
10       C0011  2026-01-12          5   397.95   tel
11       C0012  2026-01-04          2   153.96   web
12       C0013  2026-01-25          1   399.58   web
13       C0014  2026-01-06          8    62.16   tel
14       C0015  2026-01-10          1   253.56   tel
15       C0016  2026-01-09        901    17.59   web
16       C0017  2026-01-28         11   276.12   web
17       C0018  2026-01-17          5   389.83   tel
18       C0019  2026-01-10         13   202.75   app
19       C0020  2026-01-15          7   131.33   web
20       C0021  2026-01-22          3   378.24   web
21       C0022  2026-01-12        907   167.44   app
22       C0023  2026-01-18        902   122.26   tel
23       C0024  2026-01-08          4    28.35   tel
24       C0025  2026-01-14          9   119.61   tel
25       C0026  2026-01-08        907   111.28   tel
26       C0027  2026-01-11          2   137.86   app
27       C0028  2026-01-13        900    45.40   tel
28       C0029  2026-01-19         13   169.96   tel
29       C0030  2026-01-08         11   210.43   web
30       C0031  2026-01-01          3   298.28   app
31       C0032  2026-01-20          9   283.42   web
32       C0033  2026-01-04          9    21.02   web
33       C0034  2026-01-10          9    34.70   app
34       C0035  2026-01-23        902   276.36   web
35       C0036  2026-01-21         10   375.78   tel
36       C0037  2026-01-07          1    28.16   web
37       C0038  2026-01-18          3    43.98   web
38       C0039  2026-01-14         15   317.83   tel
39       C0040  2026-01-12         15   160.47   web
40       C0041  2026-01-25          3   130.33   app
41       C0042  2026-01-06          3   269.09   app
42       C0043  2026-01-16          8   366.75   app
43       C0044  2026-01-15          5   280.16   app
44       C0045  2026-01-26          8   191.18   tel
45       C0046  2026-01-08          4   111.93   app
46       C0047  2026-01-02         13    82.05   app
47       C0048  2026-01-09          7   132.87   tel
48       C0049  2026-01-08          7    52.47   tel
49       C0050  2026-01-07          3   312.78   tel
50       C0051  2026-01-11         11   288.53   app
51       C0052  2026-01-02          1   235.54   app
52       C0053  2026-01-11          4   306.87   tel
53       C0054  2026-01-26        905    80.07   tel
54       C0055  2026-01-13         12    43.11   web
55       C0056  2026-01-08          5    38.85   tel
56       C0057  2026-01-02        901   385.67   web
57       C0058  2026-01-21        908   145.73   app
58       C0059  2026-01-08        908   142.78   tel
59       C0060  2026-01-13          1    32.12   web

Mois 2 de commandes :

   commande_id        date  client_id  montant canal
0        D0001  2026-02-04          9   260.89   tel
1        D0002  2026-02-18         11   249.49   app
2        D0003  2026-02-27          1   164.68   tel
3        D0004  2026-02-03         15    97.49   tel
4        D0005  2026-02-05         11   217.17   web
5        D0006  2026-02-26        904   122.50   tel
6        D0007  2026-02-23         10   211.83   tel
7        D0008  2026-02-23        903   177.31   tel
8        D0009  2026-02-08          3    20.29   web
9        D0010  2026-02-11         10   137.84   app
10       D0011  2026-02-11         15    30.06   app
11       D0012  2026-02-12          9   115.23   web
12       D0013  2026-02-23          8   308.58   tel
13       D0014  2026-02-24          5   132.99   app
14       D0015  2026-02-15          9   364.10   web
15       D0016  2026-02-08          4   203.62   tel
16       D0017  2026-02-06         11   102.30   app
17       D0018  2026-02-16        908    48.21   tel
18       D0019  2026-02-27         10   107.56   web
19       D0020  2026-02-10         14    92.81   tel
20       D0021  2026-02-21         15   167.39   tel
21       D0022  2026-02-12          6   215.08   app
22       D0023  2026-02-18        900   314.44   app
23       D0024  2026-02-21         13   169.28   tel
24       D0025  2026-02-06          8   149.95   web
25       D0026  2026-02-21          5   203.83   app
26       D0027  2026-02-01        904   225.25   app
27       D0028  2026-02-01         11   284.96   web
28       D0029  2026-02-09        907   256.75   web
29       D0030  2026-02-12          1   329.23   app

Mois 1 & 2 de commandes :

   commande_id        date  client_id  montant canal
0        C0001  2026-01-09        901   241.62   app
1        C0002  2026-01-13        904    28.48   web
2        C0003  2026-01-05         15    88.37   app
3        C0004  2026-01-22         13    33.94   tel
4        C0005  2026-01-23          1   299.36   tel
..         ...         ...        ...      ...   ...
85       D0026  2026-02-21          5   203.83   app
86       D0027  2026-02-01        904   225.25   app
87       D0028  2026-02-01         11   284.96   web
88       D0029  2026-02-09        907   256.75   web
89       D0030  2026-02-12          1   329.23   app

[90 rows x 5 columns]

Le CA total sur 2 mois est de 16718.6€

In [ ]:
## 6 (réflexion en commentaire)
# INNER JOIN : Garde les éléments qui correspondent dans les 2 tables si un id n'existe pas dans une table et qu'on inner join sur cet id alors il n'apparaitra pas dans la table jointe
# LEFT JOIN : Garde tous les éléments de la table gauche et remplace par NaN si pas de correspondance dans la table de droite
# Exemple : j'ai une table avec des clients et des commandes (liés par un client_id), si je veux les commandes passés par les clients enregistrés uniquement je fais un INNER JOIN avec client je vais avoir uniquement les commandes ou client_id de commandes = client_id de clients
# Mais si je fais un LEFT JOIN sur client je vais avoir toutes les commandes mais les données reliés aux clients (qui ne sont pas dans la table client mais qui sont dans commandes) seront des NaN