# Livrable Semaine 2 — Analyse exploratoire : ventes en pharmacie

**Contexte.** `data/ventes_pharmacie.csv` recense des ventes de médicaments en officine sur le 1er semestre 2026 (date, région, médicament, classe thérapeutique, nombre de boîtes vendues, prix unitaire, remboursable ou non).

**Objectif du livrable.** Mener une première exploration *de bout en bout* avec tes outils de la Semaine 2 (chargement, inspection, profilage, colonnes calculées, filtres, tops, `.str`) et **conclure par une synthèse écrite**.

## 1. Découverte du jeu de données

Charge le fichier, puis réponds : de combien de ventes parle-t-on, quelles sont les colonnes et leurs types, et y a-t-il des **valeurs manquantes** ? (Une colonne en contient.)

In [9]:
# ton code
import pandas as pd
df = pd.read_csv("data/ventes_pharmacie.csv")
df.head(5)

,date,region,medicament,classe_therapeutique,boites_vendues,prix_unitaire,remboursable
0,2026-01-03,Île-de-France,Vitamine D3 Zyma,Supplément,46,6.43,Non
1,2026-01-03,Occitanie,Ramipril 5mg,Antihypertenseur,41,4.97,Oui
2,2026-01-03,Occitanie,Lexomil 6mg,Anxiolytique,42,2.31,Oui
3,2026-01-04,Occitanie,Doliprane 1000mg,Antalgique,60,2.18,Oui
4,2026-01-04,Grand Est,Gaviscon menthe,Antiacide,43,5.22,Non

In [10]:
print(df.dtypes, "\n")
print(df.shape, "\n")
print(df["region"].isna().value_counts()) # On a bien 12 valeurs avec des valeurs manquantes (NaN)

date                        str
region                      str
medicament                  str
classe_therapeutique        str
boites_vendues            int64
prix_unitaire           float64
remboursable                str
dtype: object

(110, 7)

region
False    98
True     12
Name: count, dtype: int64

## 2. Profilage : ce qui revient le plus

Quelles **classes thérapeutiques** sont les plus représentées dans les ventes ? Et quelles **régions** ? Y a-t-il un déséquilibre ?

In [11]:
# ton code
count_classes = df["classe_therapeutique"].value_counts() # On peut remarquer que c'est les classes Antihypertenseur (18) Supplément (14) les autres sont à 9 ou moins
count_region = df["region"].value_counts(sort=True) # On peut remarquer que les régions Hauts-de-France (8) et Auvergne-Rhône-Alpes (10) sont les moins représentées les autres sont à minimum 14 apparitions

print("Sur les 110 lignes du dataset on remarque qu'il y a : ", sum(count_classes), " lignes avec une classe thérapeutique\n\n", count_classes, "\n\n")
print("Sur les 110 lignes du dataset on remarque qu'il y a : ", sum(count_region), " lignes avec une région\n\n", count_region)

# On a bien un déséquilibre

Sur les 110 lignes du dataset on remarque qu'il y a :  110  lignes avec une classe thérapeutique

 classe_therapeutique
Antihypertenseur        18
Supplément              14
Antibiotique             9
Anxiolytique             8
Antiacide                8
Antispasmodique          8
Anti-inflammatoire       8
Antalgique               6
Antidiarrhéique          6
Antidiabétique           6
Bronchodilatateur        5
Antiagrégant             5
ORL                      5
Hormone thyroïdienne     4
Name: count, dtype: int64


Sur les 110 lignes du dataset on remarque qu'il y a :  98  lignes avec une région

 region
Île-de-France           18
Grand Est               17
Occitanie               16
Bretagne                15
Normandie               14
Auvergne-Rhône-Alpes    10
Hauts-de-France          8
Name: count, dtype: int64

## 3. Construire un indicateur métier

Le nombre de boîtes ne dit pas tout : ce qui compte, c'est le **chiffre d'affaires** (CA = boîtes × prix unitaire). Crée cet indicateur par vente, puis donne le **CA total** du semestre.

In [12]:
# ton code
df["chiffre_daffaire"] = df["boites_vendues"] * df["prix_unitaire"]
df_sans_nan = df.dropna() # Plus pour m'avancer pour la suite pour mieux comprendre
ca_total_avec_nan = sum(df["chiffre_daffaire"])
ca_total_sans_nan = sum(df_sans_nan["chiffre_daffaire"])

print("Le CA total du semestre (si on compte les NaN) est de : ", ca_total_avec_nan, "\n")
print("Le CA total du semestre (si on compte les NaN) est de : ", ca_total_sans_nan, "\n")

Le CA total du semestre (si on compte les NaN) est de :  20588.32

Le CA total du semestre (si on compte les NaN) est de :  19378.68

## 4. Qui pèse le plus ?

À partir du CA et des quantités :
1. Quels sont les **5 médicaments** au plus gros chiffre d'affaires (sur une vente) ?
2. Quelle est la répartition **remboursable / non remboursable** des ventes ?
3. Isole les ventes au CA élevé (à toi de fixer un seuil pertinent et de le justifier en commentaire).

1. Quels sont les **5 médicaments** au plus gros chiffre d'affaires (sur une vente) ?

In [13]:
# ton code
top_ventes = df.nlargest(5, "chiffre_daffaire").sort_values("chiffre_daffaire", ascending=False)
top_ventes

,date,region,medicament,classe_therapeutique,boites_vendues,prix_unitaire,remboursable,chiffre_daffaire
35,2026-02-19,Hauts-de-France,Lantus 100UI,Antidiabétique,57,39.56,Oui,2254.92
55,2026-03-25,Grand Est,Lantus 100UI,Antidiabétique,54,38.64,Oui,2086.56
109,2026-06-28,Grand Est,Lantus 100UI,Antidiabétique,48,39.84,Oui,1912.32
49,2026-03-10,Hauts-de-France,Magnésium B6,Supplément,49,7.91,Non,387.59
46,2026-03-07,Occitanie,Magnésium B6,Supplément,43,8.12,Non,349.16

In [14]:
# ton code
top_prix_u = df.nlargest(5, "prix_unitaire").sort_values("prix_unitaire", ascending=False)
top_prix_u

,date,region,medicament,classe_therapeutique,boites_vendues,prix_unitaire,remboursable,chiffre_daffaire
109,2026-06-28,Grand Est,Lantus 100UI,Antidiabétique,48,39.84,Oui,1912.32
35,2026-02-19,Hauts-de-France,Lantus 100UI,Antidiabétique,57,39.56,Oui,2254.92
55,2026-03-25,Grand Est,Lantus 100UI,Antidiabétique,54,38.64,Oui,2086.56
46,2026-03-07,Occitanie,Magnésium B6,Supplément,43,8.12,Non,349.16
9,2026-01-12,Normandie,Augmentin 1g,Antibiotique,14,8.04,Oui,112.56

2. Quelle est la répartition **remboursable / non remboursable** des ventes ?

In [15]:
df_non_remboursable = df[df["remboursable"].str.contains("Non")].sort_values("medicament", ascending=False)
liste_medicaments = df_non_remboursable["medicament"].unique().tolist()

print(liste_medicaments)

['Vitamine D3 Zyma', 'Strepsils miel-citron', 'Spasfon', 'Smecta', 'Magnésium B6', 'Gaviscon menthe']

In [16]:
df_remboursable = df[df["remboursable"].str.contains("Oui")].sort_values("prix_unitaire", ascending=False)
liste_medicaments_2 = df_remboursable["medicament"].unique().tolist()

print(liste_medicaments_2)

['Lantus 100UI', 'Augmentin 1g', 'Amoxicilline 1g', 'Ramipril 5mg', 'Metformine 1000mg', 'Ventoline 100µg', 'Amlodipine 5mg', 'Levothyrox 75µg', 'Kardégic 75mg', 'Xanax 0.25mg', 'Ibuprofène 400mg', 'Lexomil 6mg', 'Doliprane 1000mg', 'Efferalgan 500mg']

In [17]:
répartition_remboursable = (df["remboursable"].str.upper() == "OUI").value_counts()
répartition_remboursable

remboursable
True     69
False    41
Name: count, dtype: int64

3. Isole les ventes au CA élevé (à toi de fixer un seuil pertinent et de le justifier en commentaire).

In [18]:
nb_ligne_valide = len(df_sans_nan)
ca_total = sum(df_sans_nan["chiffre_daffaire"])

moyenne_ca = ca_total / nb_ligne_valide
print("Moyenne du chiffre d'affaires : ", moyenne_ca)

Moyenne du chiffre d'affaires :  197.74163265306123

In [19]:
# On va prendre tout les CA au dessus de moyenne_ca
df_ca_eleve = df[df["chiffre_daffaire"] > moyenne_ca].sort_values("chiffre_daffaire")
df_ca_eleve

,date,region,medicament,classe_therapeutique,boites_vendues,prix_unitaire,remboursable,chiffre_daffaire
91,2026-06-02,Hauts-de-France,Ventoline 100µg,Bronchodilatateur,44,4.55,Oui,200.20
22,2026-02-02,Île-de-France,Gaviscon menthe,Antiacide,38,5.35,Non,203.30
69,2026-04-16,Île-de-France,Magnésium B6,Supplément,26,7.82,Non,203.32
1,2026-01-03,Occitanie,Ramipril 5mg,Antihypertenseur,41,4.97,Oui,203.77
47,2026-03-07,Occitanie,Metformine 1000mg,Antidiabétique,44,4.70,Oui,206.80
94,2026-06-06,Grand Est,Gaviscon menthe,Antiacide,43,5.08,Non,218.44
81,2026-05-10,Bretagne,Amoxicilline 1g,Antibiotique,43,5.11,Oui,219.73
78,2026-05-03,NaN,Smecta,Antidiarrhéique,55,4.04,Non,222.20
4,2026-01-04,Grand Est,Gaviscon menthe,Antiacide,43,5.22,Non,224.46
44,2026-03-03,Bretagne,Smecta,Antidiarrhéique,53,4.29,Non,227.37
43,2026-03-03,Auvergne-Rhône-Alpes,Smecta,Antidiarrhéique,57,4.06,Non,231.42
61,2026-04-07,Île-de-France,Amlodipine 5mg,Antihypertenseur,56,4.21,Oui,235.76
67,2026-04-15,Bretagne,Strepsils miel-citron,ORL,44,5.43,Non,238.92
65,2026-04-12,Normandie,Ramipril 5mg,Antihypertenseur,47,5.11,Oui,240.17
70,2026-04-20,Auvergne-Rhône-Alpes,Amoxicilline 1g,Antibiotique,48,5.01,Oui,240.48
74,2026-04-26,Grand Est,Amlodipine 5mg,Antihypertenseur,56,4.36,Oui,244.16
33,2026-02-17,Hauts-de-France,Magnésium B6,Supplément,32,7.72,Non,247.04
105,2026-06-24,Île-de-France,Amlodipine 5mg,Antihypertenseur,58,4.26,Oui,247.08
80,2026-05-10,Normandie,Smecta,Antidiarrhéique,60,4.19,Non,251.40
12,2026-01-13,Occitanie,Ventoline 100µg,Bronchodilatateur,58,4.52,Oui,262.16
11,2026-01-13,Île-de-France,Ramipril 5mg,Antihypertenseur,56,4.82,Oui,269.92
17,2026-01-24,Auvergne-Rhône-Alpes,Augmentin 1g,Antibiotique,36,7.71,Oui,277.56
51,2026-03-19,NaN,Augmentin 1g,Antibiotique,36,7.71,Oui,277.56
56,2026-03-26,Normandie,Amoxicilline 1g,Antibiotique,56,4.99,Oui,279.44
34,2026-02-18,Île-de-France,Strepsils miel-citron,ORL,50,5.74,Non,287.00
0,2026-01-03,Île-de-France,Vitamine D3 Zyma,Supplément,46,6.43,Non,295.78
14,2026-01-17,Normandie,Ramipril 5mg,Antihypertenseur,60,5.12,Oui,307.20
53,2026-03-21,Normandie,Gaviscon menthe,Antiacide,58,5.39,Non,312.62
6,2026-01-08,Île-de-France,Vitamine D3 Zyma,Supplément,53,6.13,Non,324.89
46,2026-03-07,Occitanie,Magnésium B6,Supplément,43,8.12,Non,349.16
49,2026-03-10,Hauts-de-France,Magnésium B6,Supplément,49,7.91,Non,387.59
109,2026-06-28,Grand Est,Lantus 100UI,Antidiabétique,48,39.84,Oui,1912.32
55,2026-03-25,Grand Est,Lantus 100UI,Antidiabétique,54,38.64,Oui,2086.56
35,2026-02-19,Hauts-de-France,Lantus 100UI,Antidiabétique,57,39.56,Oui,2254.92

In [20]:
# Si on avait eu le CA minimum à scoper pour la question on aurait pu écrire
# Exemple avec CA élevé minimum = 200 :

# df_ca_eleve = df[df["chiffre_daffaire"].between(200, max(df["chiffre_daffaire"]))].sort_values("chiffre_daffaire")
# df_ca_eleve

## 5. Exploration libre (au moins une manipulation de texte)

Pose-toi **une** question de ton choix et réponds-y. Contrainte : utilise au moins une fois l'accesseur `.str`.

In [21]:
# ton code (Vérifier quels lignes ont une classe qui commence par Anti)
df_classes_atc = df[df["classe_therapeutique"].str.startswith("Anti")]
df_classes_atc

,date,region,medicament,classe_therapeutique,boites_vendues,prix_unitaire,remboursable,chiffre_daffaire
1,2026-01-03,Occitanie,Ramipril 5mg,Antihypertenseur,41,4.97,Oui,203.77
4,2026-01-04,Grand Est,Gaviscon menthe,Antiacide,43,5.22,Non,224.46
9,2026-01-12,Normandie,Augmentin 1g,Antibiotique,14,8.04,Oui,112.56
10,2026-01-12,Grand Est,Amoxicilline 1g,Antibiotique,35,5.12,Oui,179.20
11,2026-01-13,Île-de-France,Ramipril 5mg,Antihypertenseur,56,4.82,Oui,269.92
...,...,...,...,...,...,...,...,...
101,2026-06-21,Bretagne,Kardégic 75mg,Antiagrégant,24,3.12,Oui,74.88
102,2026-06-21,Auvergne-Rhône-Alpes,Amlodipine 5mg,Antihypertenseur,20,4.23,Oui,84.60
105,2026-06-24,Île-de-France,Amlodipine 5mg,Antihypertenseur,58,4.26,Oui,247.08
108,2026-06-26,Auvergne-Rhône-Alpes,Spasfon,Antispasmodique,36,2.10,Non,75.60
109,2026-06-28,Grand Est,Lantus 100UI,Antidiabétique,48,39.84,Oui,1912.32

## 6. Synthèse

En 3 à 5 phrases : qu'as-tu appris sur ces ventes ?

Alors après analyse de ce dataset je me rend compte de plusieurs choses intéressantes :

- Tout d'abord la région dominante est l'île de france (ce qui n'est pas étonnant) mais suivi de très près par le Grand Est , la Bretagne, la Normandie, etc... Il n'y a que les Hauts-de-France (8) et l'Auvergne-Rhône-alpes (10) sont les moins représentées
- Lantus 100UI et Magnésium B6 sont les seuls médicaments qui apparaissent dans le top 5 des CA les plus élevé sur une seule vente (très demandées) mais également en terme de prix unitaire
- liste des médicaments non remboursables = ['Vitamine D3 Zyma', 'Strepsils miel-citron', 'Spasfon', 'Smecta', 'Magnésium B6', 'Gaviscon menthe']
- liste des médicaments remboursables = ['Lantus 100UI', 'Augmentin 1g', 'Amoxicilline 1g', 'Ramipril 5mg', 'Metformine 1000mg', 'Ventoline 100µg', 'Amlodipine 5mg', 'Levothyrox 75µg', 'Kardégic 75mg', 'Xanax 0.25mg', 'Ibuprofène 400mg', 'Lexomil 6mg', 'Doliprane 1000mg', 'Efferalgan 500mg']
- Malheureusement certaines lignes ont une région qui est NaN (Not a Number) ce qui fait que j'ai dû les retirer du dataset et de plus on a seulement une partie des régions donc le dataset est potentiellement incomplet (s'il doit être sur toutes la France)